feature/bS-3759-Align readme
build-security/opa-express-middleware pull request #11
Opened 2021-05-10 14:07 UTC by Ofir-Lapid

2021-05-20 09:30 UTC, yashtewari requested changes

2021-05-20 09:30 UTC, yashtewari commented on README.md
> +To simplify the setup process, the following example uses a local [build.security pdp instance](https://docs.build.security/policy-decision-points-pdp/pdp-deployments/standalone-docker-1).
- pdp -> PDP

2021-05-20 09:30 UTC, yashtewari commented on README.md
> +If you are already familiar with how to run your PDP (Policy Decision Point), You can also run a pdp on you environment (Dev/Prod, etc).
- pdp -> PDP

2021-05-20 09:30 UTC, yashtewari commented on README.md
> +[build.security](https://docs.build.security/) provides simple development and management of the organization's authorization policy.
- of the organization's -> for your organization's

2021-05-20 09:30 UTC, yashtewari commented on README.md
> +opa-express-middleware is a Node.js express middleware intended for performing authorizing requests against build.security pdp/[OPA](https://www.openpolicyagent.org/).
- express middleware -> Express framework middleware
- intended for performing authorizing requests -> intended to perform authz
- pdp -> PDP

2021-05-23 08:41 UTC, Ofir-Lapid commented on README.md
> +opa-express-middleware is a Node.js express middleware intended for performing authorizing requests against build.security pdp/[OPA](https://www.openpolicyagent.org/).
Changed to - intended for performing autorization requests...

2021-05-23 09:56 UTC, yashtewari approved these changes

2021-05-23 11:05 UTC, merged